#!/bin/bash

cd
rm -rf AUTORUN-CCMINER-AUN1.2
git clone https://github.com/Aunminer/AUTORUN-CCMINER-AUN
cd ../etc/mobile-mining/set-miner
cp -r online.json offline.json /../root/AUTORUN-CCMINER-AUN/mobile-mining/set-miner
cd
cd ../etc
rm -rf mobile-mining
cd
cd ../bin
rm -rf add-ip edit-miner run-miner update down-grade
cd
cd AUTORUN-CCMINER-AUN
chmod +x setupdate.sh
sh setupdate.sh
